-- AUTO-GENERATED by scripts/generate-seed-sql.ts — do not edit by hand.
-- Deterministic demo dataset shared with the browser demo mode.
-- Run schema.sql first, then this file.

begin;

-- Idempotent: wipe only the demo tables, keep the schema.
truncate table notifications, order_events, attachments, service_reports, orders cascade;

insert into orders (order_no, customer_name, phone, address, problem_description, service_type, quoted_price, assigned_technician, status, admin_notes, created_at, updated_at) values
  ('SS-2026-0001', 'Siti Nurhaliza', '013-7788990', 'B-3-2 Pangsapuri Melati, Klang', 'Water dripping from indoor unit', 'Inspection', 680, 'Bala', 'In Progress', 'Customer prefers morning slot.', '2026-08-29T01:03:00.000Z', '2026-08-29T01:03:00.000Z'),
  ('SS-2026-0002', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Water dripping from indoor unit', 'Repair', 320, 'Ali', 'Job Done', '', '2026-08-29T02:53:00.000Z', '2026-08-29T02:53:00.000Z'),
  ('SS-2026-0003', 'Lim Chee Keong', '016-2233445', '88 Jalan Bayan, Petaling Jaya', 'Compressor trips the breaker after 10 minutes', 'Repair', 150, 'Bala', 'Closed', '', '2026-08-29T01:19:00.000Z', '2026-08-29T01:19:00.000Z'),
  ('SS-2026-0004', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Loud noise from outdoor compressor', 'Inspection', 80, 'Ali', 'Reviewed', '', '2026-08-30T01:30:00.000Z', '2026-08-30T01:30:00.000Z'),
  ('SS-2026-0005', 'Ahmad Zaki', '012-3456789', 'No. 12, Jalan Sejuk, Shah Alam', 'Annual chemical cleaning for 2 units', 'Cleaning', 220, 'Bala', 'Closed', '', '2026-08-30T04:29:00.000Z', '2026-08-30T04:29:00.000Z'),
  ('SS-2026-0006', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Bad smell when unit runs', 'Cleaning', 120, 'Yusoff', 'Closed', '', '2026-08-30T03:38:00.000Z', '2026-08-30T03:38:00.000Z'),
  ('SS-2026-0007', 'Tan Wei Ling', '019-3344556', '22 Jalan Indah, Cheras', 'New unit installation for master bedroom', 'Cleaning', 150, 'Yusoff', 'Reviewed', 'Customer prefers morning slot.', '2026-08-31T01:12:00.000Z', '2026-08-31T01:12:00.000Z'),
  ('SS-2026-0008', 'Kumaravel S.', '012-9988776', '15 Jalan Perdana, Kajang', 'Remote not responding, unit beeping', 'Repair', 150, 'Yusoff', 'Closed', '', '2026-08-31T03:13:00.000Z', '2026-08-31T03:13:00.000Z'),
  ('SS-2026-0009', 'Siti Nurhaliza', '013-7788990', 'B-3-2 Pangsapuri Melati, Klang', 'Bad smell when unit runs', 'Gas Refill', 680, 'Ali', 'Assigned', '', '2026-08-31T02:33:00.000Z', '2026-08-31T02:33:00.000Z'),
  ('SS-2026-0010', 'Syafiq Rahman', '014-8899001', 'No. 3, Jalan Bukit, Gombak', 'Compressor trips the breaker after 10 minutes', 'Gas Refill', 220, 'Bala', 'Job Done', '', '2026-09-01T01:24:00.000Z', '2026-09-01T01:24:00.000Z'),
  ('SS-2026-0011', 'Lim Chee Keong', '016-2233445', '88 Jalan Bayan, Petaling Jaya', 'Loud noise from outdoor compressor', 'Repair', 120, 'Yusoff', 'Job Done', '', '2026-09-01T03:47:00.000Z', '2026-09-01T03:47:00.000Z'),
  ('SS-2026-0012', 'Kumaravel S.', '012-9988776', '15 Jalan Perdana, Kajang', 'Compressor trips the breaker after 10 minutes', 'Installation', 180, 'John', 'Closed', '', '2026-09-01T04:35:00.000Z', '2026-09-01T04:35:00.000Z'),
  ('SS-2026-0013', 'Kumaravel S.', '012-9988776', '15 Jalan Perdana, Kajang', 'Bad smell when unit runs', 'Installation', 180, 'Ali', 'Job Done', 'Customer prefers morning slot.', '2026-09-02T04:23:00.000Z', '2026-09-02T04:23:00.000Z'),
  ('SS-2026-0014', 'Syafiq Rahman', '014-8899001', 'No. 3, Jalan Bukit, Gombak', 'Aircond not cold, likely needs gas top-up', 'Inspection', 120, 'Ali', 'Job Done', '', '2026-09-02T04:09:00.000Z', '2026-09-02T04:09:00.000Z'),
  ('SS-2026-0015', 'Lim Chee Keong', '016-2233445', '88 Jalan Bayan, Petaling Jaya', 'Loud noise from outdoor compressor', 'Installation', 320, 'John', 'Assigned', 'Customer prefers morning slot.', '2026-09-02T01:49:00.000Z', '2026-09-02T01:49:00.000Z'),
  ('SS-2026-0016', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Water dripping from indoor unit', 'Installation', 180, 'Ali', 'Closed', '', '2026-09-03T01:34:00.000Z', '2026-09-03T01:34:00.000Z'),
  ('SS-2026-0017', 'Rajesh Kumar', '017-5566778', 'No. 5, Lorong Aman, Subang Jaya', 'New unit installation for master bedroom', 'Repair', 120, 'John', 'Job Done', '', '2026-09-03T02:09:00.000Z', '2026-09-03T02:09:00.000Z'),
  ('SS-2026-0018', 'Kumaravel S.', '012-9988776', '15 Jalan Perdana, Kajang', 'Indoor unit leaking into ceiling', 'Installation', 180, 'Ali', 'Closed', 'Customer prefers morning slot.', '2026-09-03T02:32:00.000Z', '2026-09-03T02:32:00.000Z'),
  ('SS-2026-0019', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'New unit installation for master bedroom', 'Gas Refill', 260, 'Ali', 'Job Done', '', '2026-09-04T01:16:00.000Z', '2026-09-04T01:16:00.000Z'),
  ('SS-2026-0020', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'New unit installation for master bedroom', 'Installation', 220, 'John', 'Closed', '', '2026-09-04T03:43:00.000Z', '2026-09-04T03:43:00.000Z'),
  ('SS-2026-0021', 'Lim Chee Keong', '016-2233445', '88 Jalan Bayan, Petaling Jaya', 'Water dripping from indoor unit', 'Cleaning', 150, 'Bala', 'Closed', 'Customer prefers morning slot.', '2026-09-04T02:05:00.000Z', '2026-09-04T02:05:00.000Z'),
  ('SS-2026-0022', 'Nurul Aina', '018-7766554', 'A-12-3 Residensi Harmoni, Puchong', 'Routine service for 3 units, office floor 2', 'Repair', 260, 'John', 'Reviewed', '', '2026-09-05T02:08:00.000Z', '2026-09-05T02:08:00.000Z'),
  ('SS-2026-0023', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'New unit installation for master bedroom', 'Installation', 680, 'Bala', 'Closed', '', '2026-09-05T01:35:00.000Z', '2026-09-05T01:35:00.000Z'),
  ('SS-2026-0024', 'Nurul Aina', '018-7766554', 'A-12-3 Residensi Harmoni, Puchong', 'Aircond not cold, likely needs gas top-up', 'Cleaning', 120, 'John', 'Closed', '', '2026-09-05T03:22:00.000Z', '2026-09-05T03:22:00.000Z'),
  ('SS-2026-0025', 'Tan Wei Ling', '019-3344556', '22 Jalan Indah, Cheras', 'Annual chemical cleaning for 2 units', 'Repair', 150, 'Yusoff', 'Closed', '', '2026-09-06T04:09:00.000Z', '2026-09-06T04:09:00.000Z'),
  ('SS-2026-0026', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Annual chemical cleaning for 2 units', 'Cleaning', 220, 'Bala', 'Job Done', '', '2026-09-06T04:57:00.000Z', '2026-09-06T04:57:00.000Z'),
  ('SS-2026-0027', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Loud noise from outdoor compressor', 'Inspection', 80, 'Bala', 'Closed', 'Customer prefers morning slot.', '2026-09-06T03:09:00.000Z', '2026-09-06T03:09:00.000Z'),
  ('SS-2026-0028', 'Ahmad Zaki', '012-3456789', 'No. 12, Jalan Sejuk, Shah Alam', 'New unit installation for master bedroom', 'Gas Refill', 320, 'Bala', 'Closed', '', '2026-09-07T03:29:00.000Z', '2026-09-07T03:29:00.000Z'),
  ('SS-2026-0029', 'Syafiq Rahman', '014-8899001', 'No. 3, Jalan Bukit, Gombak', 'Routine service for 3 units, office floor 2', 'Repair', 150, 'Bala', 'Closed', '', '2026-09-07T01:51:00.000Z', '2026-09-07T01:51:00.000Z'),
  ('SS-2026-0030', 'Rajesh Kumar', '017-5566778', 'No. 5, Lorong Aman, Subang Jaya', 'Indoor unit leaking into ceiling', 'Gas Refill', 450, 'Ali', 'Closed', 'Customer prefers morning slot.', '2026-09-07T01:21:00.000Z', '2026-09-07T01:21:00.000Z'),
  ('SS-2026-0031', 'Nurul Aina', '018-7766554', 'A-12-3 Residensi Harmoni, Puchong', 'New unit installation for master bedroom', 'Inspection', 450, 'Ali', 'Job Done', 'Customer prefers morning slot.', '2026-09-08T04:49:00.000Z', '2026-09-08T04:49:00.000Z'),
  ('SS-2026-0032', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'New unit installation for master bedroom', 'Cleaning', 80, 'Yusoff', 'Closed', 'Customer prefers morning slot.', '2026-09-08T04:28:00.000Z', '2026-09-08T04:28:00.000Z'),
  ('SS-2026-0033', 'Syafiq Rahman', '014-8899001', 'No. 3, Jalan Bukit, Gombak', 'Compressor trips the breaker after 10 minutes', 'Inspection', 80, 'Bala', 'Closed', 'Customer prefers morning slot.', '2026-09-08T04:08:00.000Z', '2026-09-08T04:08:00.000Z'),
  ('SS-2026-0034', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Routine service for 3 units, office floor 2', 'Installation', 450, 'Ali', 'Job Done', '', '2026-09-09T03:33:00.000Z', '2026-09-09T03:33:00.000Z'),
  ('SS-2026-0035', 'Lim Chee Keong', '016-2233445', '88 Jalan Bayan, Petaling Jaya', 'Aircond not cold, likely needs gas top-up', 'Gas Refill', 80, 'John', 'Reviewed', 'Customer prefers morning slot.', '2026-09-09T03:18:00.000Z', '2026-09-09T03:18:00.000Z'),
  ('SS-2026-0036', 'Kumaravel S.', '012-9988776', '15 Jalan Perdana, Kajang', 'Bad smell when unit runs', 'Gas Refill', 450, 'John', 'Reviewed', '', '2026-09-09T02:28:00.000Z', '2026-09-09T02:28:00.000Z'),
  ('SS-2026-0037', 'Ahmad Zaki', '012-3456789', 'No. 12, Jalan Sejuk, Shah Alam', 'Bad smell when unit runs', 'Gas Refill', 680, 'Ali', 'Reviewed', 'Customer prefers morning slot.', '2026-09-10T04:10:00.000Z', '2026-09-10T04:10:00.000Z'),
  ('SS-2026-0038', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Loud noise from outdoor compressor', 'Repair', 260, 'Ali', 'Closed', 'Customer prefers morning slot.', '2026-09-10T01:10:00.000Z', '2026-09-10T01:10:00.000Z'),
  ('SS-2026-0039', 'Rajesh Kumar', '017-5566778', 'No. 5, Lorong Aman, Subang Jaya', 'Compressor trips the breaker after 10 minutes', 'Inspection', 320, 'John', 'Closed', '', '2026-09-10T02:42:00.000Z', '2026-09-10T02:42:00.000Z'),
  ('SS-2026-0040', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Compressor trips the breaker after 10 minutes', 'Repair', 260, 'John', 'Job Done', '', '2026-09-11T01:37:00.000Z', '2026-09-11T01:37:00.000Z'),
  ('SS-2026-0041', 'Faridah Hassan', '011-22334455', 'No. 9, Jalan Damai, Ampang', 'Remote not responding, unit beeping', 'Inspection', 180, 'Yusoff', 'In Progress', '', '2026-09-11T02:43:00.000Z', '2026-09-11T02:43:00.000Z'),
  ('SS-2026-0042', 'Ahmad Zaki', '012-3456789', 'No. 12, Jalan Sejuk, Shah Alam', 'Aircond not cold, likely needs gas top-up', 'Installation', 320, 'Ali', 'In Progress', '', '2026-09-11T04:36:00.000Z', '2026-09-11T04:36:00.000Z'),
  ('SS-2026-0043', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Compressor trips the breaker after 10 minutes', 'Installation', 450, 'Ali', 'Job Done', '', '2026-09-12T01:58:00.000Z', '2026-09-12T01:58:00.000Z'),
  ('SS-2026-0044', 'Wong Kah Meng', '016-1122334', '77 Jalan Utama, Kepong', 'Water dripping from indoor unit', 'Cleaning', 150, 'Bala', 'Reviewed', 'Customer prefers morning slot.', '2026-09-12T02:18:00.000Z', '2026-09-12T02:18:00.000Z'),
  ('SS-2026-0045', 'Syafiq Rahman', '014-8899001', 'No. 3, Jalan Bukit, Gombak', 'Loud noise from outdoor compressor', 'Installation', 450, 'Yusoff', 'Job Done', '', '2026-09-12T01:21:00.000Z', '2026-09-12T01:21:00.000Z');

insert into service_reports (order_no, work_done, extra_charges, final_amount, remarks, technician_name, completed_at, payment_amount, payment_method) values
  ('SS-2026-0002', 'Repaired condensate leak, added insulation wrap along the drain route.', 0, 320, 'Ladder access needed, work completed safely.', 'Ali', '2026-08-29T07:06:00.000Z', 320, 'DuitNow QR'),
  ('SS-2026-0003', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 0, 150, 'Ladder access needed, work completed safely.', 'Bala', '2026-08-29T06:48:00.000Z', 150, 'Cash'),
  ('SS-2026-0004', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 25, 105, 'Ladder access needed, work completed safely.', 'Ali', '2026-08-30T08:09:00.000Z', 105, 'Bank Transfer'),
  ('SS-2026-0005', 'Replaced remote control receiver board and tested all modes.', 0, 220, 'Unit is old (2014); advised replacement if issue returns.', 'Bala', '2026-08-30T04:31:00.000Z', 220, 'DuitNow QR'),
  ('SS-2026-0006', 'Serviced 3 units: coil cleaning, filter wash, gas pressure check, drain flush.', 0, 120, 'Unit is old (2014); advised replacement if issue returns.', 'Yusoff', '2026-08-30T08:03:00.000Z', null, null),
  ('SS-2026-0007', 'Cleared blocked drain pipe, flushed drainage tray, sealed minor leak at joint.', 40, 190, 'Customer satisfied, advised next service in 6 months.', 'Yusoff', '2026-08-31T03:53:00.000Z', 190, 'DuitNow QR'),
  ('SS-2026-0008', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 15, 165, '', 'Yusoff', '2026-08-31T04:10:00.000Z', 165, 'Bank Transfer'),
  ('SS-2026-0010', 'Cleared blocked drain pipe, flushed drainage tray, sealed minor leak at joint.', 0, 220, '', 'Bala', '2026-09-01T06:23:00.000Z', 220, 'Cash'),
  ('SS-2026-0011', 'Replaced remote control receiver board and tested all modes.', 15, 135, 'Customer asked for quotation for a second unit.', 'Yusoff', '2026-09-01T07:05:00.000Z', 135, 'Cash'),
  ('SS-2026-0012', 'Repaired condensate leak, added insulation wrap along the drain route.', 90, 270, 'Customer asked for quotation for a second unit.', 'John', '2026-09-01T08:13:00.000Z', 270, 'DuitNow QR'),
  ('SS-2026-0013', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 0, 180, 'Customer satisfied, advised next service in 6 months.', 'Ali', '2026-09-02T05:03:00.000Z', null, null),
  ('SS-2026-0014', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 60, 180, 'Customer asked for quotation for a second unit.', 'Ali', '2026-09-02T03:54:00.000Z', 180, 'Bank Transfer'),
  ('SS-2026-0016', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 0, 180, 'Customer asked for quotation for a second unit.', 'Ali', '2026-09-03T07:49:00.000Z', 180, 'DuitNow QR'),
  ('SS-2026-0017', 'Replaced faulty capacitor, topped up R32 gas, tested cooling for 20 minutes.', 60, 180, 'Unit is old (2014); advised replacement if issue returns.', 'John', '2026-09-03T06:57:00.000Z', 180, 'Bank Transfer'),
  ('SS-2026-0018', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 0, 180, 'Unit is old (2014); advised replacement if issue returns.', 'Ali', '2026-09-03T04:07:00.000Z', 180, 'DuitNow QR'),
  ('SS-2026-0019', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 0, 260, 'Ladder access needed, work completed safely.', 'Ali', '2026-09-04T07:09:00.000Z', 260, 'Bank Transfer'),
  ('SS-2026-0020', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 0, 220, 'Customer asked for quotation for a second unit.', 'John', '2026-09-04T04:49:00.000Z', null, null),
  ('SS-2026-0021', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 0, 150, 'Unit is old (2014); advised replacement if issue returns.', 'Bala', '2026-09-04T08:58:00.000Z', null, null),
  ('SS-2026-0022', 'Replaced faulty capacitor, topped up R32 gas, tested cooling for 20 minutes.', 15, 275, '', 'John', '2026-09-05T07:46:00.000Z', 275, 'DuitNow QR'),
  ('SS-2026-0023', 'Cleared blocked drain pipe, flushed drainage tray, sealed minor leak at joint.', 0, 680, '', 'Bala', '2026-09-05T04:46:00.000Z', 680, 'DuitNow QR'),
  ('SS-2026-0024', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 0, 120, 'Ladder access needed, work completed safely.', 'John', '2026-09-05T03:56:00.000Z', 120, 'Bank Transfer'),
  ('SS-2026-0025', 'Installed new 1.5HP unit, ran new copper piping, vacuumed system, tested operation.', 60, 210, '', 'Yusoff', '2026-09-06T06:27:00.000Z', 210, 'DuitNow QR'),
  ('SS-2026-0026', 'Replaced faulty capacitor, topped up R32 gas, tested cooling for 20 minutes.', 0, 220, 'Unit is old (2014); advised replacement if issue returns.', 'Bala', '2026-09-06T07:49:00.000Z', null, null),
  ('SS-2026-0027', 'Repaired condensate leak, added insulation wrap along the drain route.', 0, 80, 'Ladder access needed, work completed safely.', 'Bala', '2026-09-06T05:12:00.000Z', null, null),
  ('SS-2026-0028', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 60, 380, 'Ladder access needed, work completed safely.', 'Bala', '2026-09-07T05:59:00.000Z', 380, 'Cash'),
  ('SS-2026-0029', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 0, 150, 'Customer satisfied, advised next service in 6 months.', 'Bala', '2026-09-07T03:07:00.000Z', 150, 'Cash'),
  ('SS-2026-0030', 'Repaired condensate leak, added insulation wrap along the drain route.', 0, 450, 'Unit is old (2014); advised replacement if issue returns.', 'Ali', '2026-09-07T03:26:00.000Z', 450, 'DuitNow QR'),
  ('SS-2026-0031', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 60, 510, 'Ladder access needed, work completed safely.', 'Ali', '2026-09-08T04:47:00.000Z', 510, 'Bank Transfer'),
  ('SS-2026-0032', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 40, 120, 'Customer satisfied, advised next service in 6 months.', 'Yusoff', '2026-09-08T05:31:00.000Z', null, null),
  ('SS-2026-0033', 'Deep cleaned blower wheel and evaporator coil, applied antibacterial treatment.', 0, 80, 'Customer satisfied, advised next service in 6 months.', 'Bala', '2026-09-08T04:48:00.000Z', 80, 'DuitNow QR'),
  ('SS-2026-0034', 'Repaired condensate leak, added insulation wrap along the drain route.', 0, 450, '', 'Ali', '2026-09-09T03:51:00.000Z', 450, 'Bank Transfer'),
  ('SS-2026-0035', 'Deep cleaned blower wheel and evaporator coil, applied antibacterial treatment.', 0, 80, '', 'John', '2026-09-09T06:45:00.000Z', 80, 'Bank Transfer'),
  ('SS-2026-0036', 'Replaced remote control receiver board and tested all modes.', 60, 510, 'Ladder access needed, work completed safely.', 'John', '2026-09-09T06:31:00.000Z', null, null),
  ('SS-2026-0037', 'Repaired condensate leak, added insulation wrap along the drain route.', 0, 680, '', 'Ali', '2026-09-10T05:09:00.000Z', 680, 'DuitNow QR'),
  ('SS-2026-0038', 'Replaced remote control receiver board and tested all modes.', 0, 260, 'Unit is old (2014); advised replacement if issue returns.', 'Ali', '2026-09-10T08:59:00.000Z', 260, 'Bank Transfer'),
  ('SS-2026-0039', 'Replaced faulty capacitor, topped up R32 gas, tested cooling for 20 minutes.', 15, 335, 'Ladder access needed, work completed safely.', 'John', '2026-09-10T08:27:00.000Z', 335, 'Cash'),
  ('SS-2026-0040', 'Dismantled and chemically cleaned indoor + outdoor unit, replaced dirty filter, gas pressure checked.', 60, 320, 'Customer satisfied, advised next service in 6 months.', 'John', '2026-09-11T04:16:00.000Z', 320, 'Bank Transfer'),
  ('SS-2026-0043', 'Replaced remote control receiver board and tested all modes.', 0, 450, 'Customer asked for quotation for a second unit.', 'Ali', '2026-09-12T08:33:00.000Z', 450, 'Cash'),
  ('SS-2026-0044', 'Cleared blocked drain pipe, flushed drainage tray, sealed minor leak at joint.', 0, 150, 'Customer satisfied, advised next service in 6 months.', 'Bala', '2026-09-12T07:00:00.000Z', 150, 'DuitNow QR'),
  ('SS-2026-0045', 'Replaced compressor start relay, verified amp draw is within spec.', 0, 450, 'Ladder access needed, work completed safely.', 'Yusoff', '2026-09-12T03:42:00.000Z', null, null);

-- Attachment rows are linked by order_no because the report UUIDs are generated by the database.
insert into attachments (report_id, name, mime, size, url)
select sr.id, v.name, v.mime, v.size, v.url
from (values
  ('SS-2026-0002', 'job-SS-2026-0002-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0002', 'job-SS-2026-0002-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0004', 'job-SS-2026-0004-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0004', 'job-SS-2026-0004-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0004', 'job-SS-2026-0004-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0005', 'job-SS-2026-0005-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0005', 'job-SS-2026-0005-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0006', 'job-SS-2026-0006-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0006', 'job-SS-2026-0006-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0006', 'job-SS-2026-0006-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0007', 'job-SS-2026-0007-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0007', 'job-SS-2026-0007-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0008', 'job-SS-2026-0008-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0010', 'job-SS-2026-0010-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0011', 'job-SS-2026-0011-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0011', 'job-SS-2026-0011-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0011', 'job-SS-2026-0011-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0012', 'job-SS-2026-0012-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0017', 'job-SS-2026-0017-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0017', 'job-SS-2026-0017-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0019', 'job-SS-2026-0019-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0020', 'job-SS-2026-0020-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0022', 'job-SS-2026-0022-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0022', 'job-SS-2026-0022-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0022', 'job-SS-2026-0022-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0024', 'job-SS-2026-0024-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0025', 'job-SS-2026-0025-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0025', 'job-SS-2026-0025-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0025', 'job-SS-2026-0025-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0026', 'job-SS-2026-0026-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0027', 'job-SS-2026-0027-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0027', 'job-SS-2026-0027-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0027', 'job-SS-2026-0027-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0028', 'job-SS-2026-0028-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0028', 'job-SS-2026-0028-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0028', 'job-SS-2026-0028-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0029', 'job-SS-2026-0029-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0029', 'job-SS-2026-0029-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0032', 'job-SS-2026-0032-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0033', 'job-SS-2026-0033-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0033', 'job-SS-2026-0033-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0033', 'job-SS-2026-0033-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0034', 'job-SS-2026-0034-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0035', 'job-SS-2026-0035-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0035', 'job-SS-2026-0035-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0036', 'job-SS-2026-0036-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0037', 'job-SS-2026-0037-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0037', 'job-SS-2026-0037-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0038', 'job-SS-2026-0038-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0039', 'job-SS-2026-0039-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0039', 'job-SS-2026-0039-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0039', 'job-SS-2026-0039-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0040', 'job-SS-2026-0040-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0043', 'job-SS-2026-0043-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0043', 'job-SS-2026-0043-2.jpg', 'image/jpeg', 192000, ''),
  ('SS-2026-0043', 'job-SS-2026-0043-3.jpg', 'image/jpeg', 204000, ''),
  ('SS-2026-0044', 'job-SS-2026-0044-1.jpg', 'image/jpeg', 180000, ''),
  ('SS-2026-0045', 'job-SS-2026-0045-1.jpg', 'image/jpeg', 180000, '')
) as v(order_no, name, mime, size, url)
join service_reports sr on sr.order_no = v.order_no;

insert into order_events (order_no, event_type, actor_role, actor_name, detail, created_at) values
  ('SS-2026-0001', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 680.00', '2026-08-29T01:03:00.000Z'),
  ('SS-2026-0001', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-08-29T02:00:00.000Z'),
  ('SS-2026-0002', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 320.00', '2026-08-29T02:53:00.000Z'),
  ('SS-2026-0002', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-08-29T03:00:00.000Z'),
  ('SS-2026-0002', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 320.00 (quoted RM 320.00 + extra RM 0.00)', '2026-08-29T07:06:00.000Z'),
  ('SS-2026-0002', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-08-29T07:07:00.000Z'),
  ('SS-2026-0002', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 320.00 via DuitNow QR', '2026-08-29T07:08:00.000Z'),
  ('SS-2026-0002', 'rescheduled', 'Admin', 'Admin (desk)', 'Customer not available — rescheduled.', '2026-08-29T06:00:00.000Z'),
  ('SS-2026-0003', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-08-29T01:19:00.000Z'),
  ('SS-2026-0003', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-08-29T02:00:00.000Z'),
  ('SS-2026-0003', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 150.00 (quoted RM 150.00 + extra RM 0.00)', '2026-08-29T06:48:00.000Z'),
  ('SS-2026-0003', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Lim Chee Keong', '2026-08-29T06:49:00.000Z'),
  ('SS-2026-0003', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 150.00 via Cash', '2026-08-29T06:50:00.000Z'),
  ('SS-2026-0003', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-08-30T02:30:00.000Z'),
  ('SS-2026-0003', 'closed', 'Manager', 'Manager', 'Closed.', '2026-08-30T03:30:00.000Z'),
  ('SS-2026-0004', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 80.00', '2026-08-30T01:30:00.000Z'),
  ('SS-2026-0004', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-08-30T02:00:00.000Z'),
  ('SS-2026-0004', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 105.00 (quoted RM 80.00 + extra RM 25.00)', '2026-08-30T08:09:00.000Z'),
  ('SS-2026-0004', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-08-30T08:10:00.000Z'),
  ('SS-2026-0004', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 105.00 via Bank Transfer', '2026-08-30T08:11:00.000Z'),
  ('SS-2026-0004', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-08-31T02:30:00.000Z'),
  ('SS-2026-0005', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 220.00', '2026-08-30T04:29:00.000Z'),
  ('SS-2026-0005', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-08-30T05:00:00.000Z'),
  ('SS-2026-0005', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 220.00 (quoted RM 220.00 + extra RM 0.00)', '2026-08-30T04:31:00.000Z'),
  ('SS-2026-0005', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Ahmad Zaki', '2026-08-30T04:32:00.000Z'),
  ('SS-2026-0005', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 220.00 via DuitNow QR', '2026-08-30T04:33:00.000Z'),
  ('SS-2026-0005', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-08-31T02:30:00.000Z'),
  ('SS-2026-0005', 'closed', 'Manager', 'Manager', 'Closed.', '2026-08-31T03:30:00.000Z'),
  ('SS-2026-0006', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 120.00', '2026-08-30T03:38:00.000Z'),
  ('SS-2026-0006', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-08-30T04:00:00.000Z'),
  ('SS-2026-0006', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 120.00 (quoted RM 120.00 + extra RM 0.00)', '2026-08-30T08:03:00.000Z'),
  ('SS-2026-0006', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-08-30T08:04:00.000Z'),
  ('SS-2026-0006', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-08-31T02:30:00.000Z'),
  ('SS-2026-0006', 'closed', 'Manager', 'Manager', 'Closed.', '2026-08-31T03:30:00.000Z'),
  ('SS-2026-0007', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-08-31T01:12:00.000Z'),
  ('SS-2026-0007', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-08-31T02:00:00.000Z'),
  ('SS-2026-0007', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 190.00 (quoted RM 150.00 + extra RM 40.00)', '2026-08-31T03:53:00.000Z'),
  ('SS-2026-0007', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Tan Wei Ling', '2026-08-31T03:54:00.000Z'),
  ('SS-2026-0007', 'payment_recorded', 'Technician', 'Yusoff', 'Payment RM 190.00 via DuitNow QR', '2026-08-31T03:55:00.000Z'),
  ('SS-2026-0007', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-01T02:30:00.000Z'),
  ('SS-2026-0008', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-08-31T03:13:00.000Z'),
  ('SS-2026-0008', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-08-31T04:00:00.000Z'),
  ('SS-2026-0008', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 165.00 (quoted RM 150.00 + extra RM 15.00)', '2026-08-31T04:10:00.000Z'),
  ('SS-2026-0008', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Kumaravel S.', '2026-08-31T04:11:00.000Z'),
  ('SS-2026-0008', 'payment_recorded', 'Technician', 'Yusoff', 'Payment RM 165.00 via Bank Transfer', '2026-08-31T04:12:00.000Z'),
  ('SS-2026-0008', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-01T02:30:00.000Z'),
  ('SS-2026-0008', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-01T03:30:00.000Z'),
  ('SS-2026-0009', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 680.00', '2026-08-31T02:33:00.000Z'),
  ('SS-2026-0009', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-08-31T03:00:00.000Z'),
  ('SS-2026-0010', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 220.00', '2026-09-01T01:24:00.000Z'),
  ('SS-2026-0010', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-01T02:00:00.000Z'),
  ('SS-2026-0010', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 220.00 (quoted RM 220.00 + extra RM 0.00)', '2026-09-01T06:23:00.000Z'),
  ('SS-2026-0010', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Syafiq Rahman', '2026-09-01T06:24:00.000Z'),
  ('SS-2026-0010', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 220.00 via Cash', '2026-09-01T06:25:00.000Z'),
  ('SS-2026-0011', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 120.00', '2026-09-01T03:47:00.000Z'),
  ('SS-2026-0011', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-09-01T04:00:00.000Z'),
  ('SS-2026-0011', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 135.00 (quoted RM 120.00 + extra RM 15.00)', '2026-09-01T07:05:00.000Z'),
  ('SS-2026-0011', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Lim Chee Keong', '2026-09-01T07:06:00.000Z'),
  ('SS-2026-0011', 'payment_recorded', 'Technician', 'Yusoff', 'Payment RM 135.00 via Cash', '2026-09-01T07:07:00.000Z'),
  ('SS-2026-0012', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 180.00', '2026-09-01T04:35:00.000Z'),
  ('SS-2026-0012', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-01T05:00:00.000Z'),
  ('SS-2026-0012', 'completed', 'Technician', 'John', 'Job done — final amount RM 270.00 (quoted RM 180.00 + extra RM 90.00)', '2026-09-01T08:13:00.000Z'),
  ('SS-2026-0012', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Kumaravel S.', '2026-09-01T08:14:00.000Z'),
  ('SS-2026-0012', 'payment_recorded', 'Technician', 'John', 'Payment RM 270.00 via DuitNow QR', '2026-09-01T08:15:00.000Z'),
  ('SS-2026-0012', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-02T02:30:00.000Z'),
  ('SS-2026-0012', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-02T03:30:00.000Z'),
  ('SS-2026-0012', 'rescheduled', 'Admin', 'Admin (desk)', 'Customer not available — rescheduled.', '2026-09-01T06:00:00.000Z'),
  ('SS-2026-0013', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 180.00', '2026-09-02T04:23:00.000Z'),
  ('SS-2026-0013', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-02T05:00:00.000Z'),
  ('SS-2026-0013', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 180.00 (quoted RM 180.00 + extra RM 0.00)', '2026-09-02T05:03:00.000Z'),
  ('SS-2026-0013', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Kumaravel S.', '2026-09-02T05:04:00.000Z'),
  ('SS-2026-0014', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 120.00', '2026-09-02T04:09:00.000Z'),
  ('SS-2026-0014', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-02T05:00:00.000Z'),
  ('SS-2026-0014', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 180.00 (quoted RM 120.00 + extra RM 60.00)', '2026-09-02T03:54:00.000Z'),
  ('SS-2026-0014', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Syafiq Rahman', '2026-09-02T03:55:00.000Z'),
  ('SS-2026-0014', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 180.00 via Bank Transfer', '2026-09-02T03:56:00.000Z'),
  ('SS-2026-0014', 'rescheduled', 'Admin', 'Admin (desk)', 'Customer not available — rescheduled.', '2026-09-02T06:00:00.000Z'),
  ('SS-2026-0015', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 320.00', '2026-09-02T01:49:00.000Z'),
  ('SS-2026-0015', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-02T02:00:00.000Z'),
  ('SS-2026-0016', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 180.00', '2026-09-03T01:34:00.000Z'),
  ('SS-2026-0016', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-03T02:00:00.000Z'),
  ('SS-2026-0016', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 180.00 (quoted RM 180.00 + extra RM 0.00)', '2026-09-03T07:49:00.000Z'),
  ('SS-2026-0016', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-03T07:50:00.000Z'),
  ('SS-2026-0016', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 180.00 via DuitNow QR', '2026-09-03T07:51:00.000Z'),
  ('SS-2026-0016', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-04T02:30:00.000Z'),
  ('SS-2026-0016', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-04T03:30:00.000Z'),
  ('SS-2026-0017', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 120.00', '2026-09-03T02:09:00.000Z'),
  ('SS-2026-0017', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-03T03:00:00.000Z'),
  ('SS-2026-0017', 'completed', 'Technician', 'John', 'Job done — final amount RM 180.00 (quoted RM 120.00 + extra RM 60.00)', '2026-09-03T06:57:00.000Z'),
  ('SS-2026-0017', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Rajesh Kumar', '2026-09-03T06:58:00.000Z'),
  ('SS-2026-0017', 'payment_recorded', 'Technician', 'John', 'Payment RM 180.00 via Bank Transfer', '2026-09-03T06:59:00.000Z'),
  ('SS-2026-0018', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 180.00', '2026-09-03T02:32:00.000Z'),
  ('SS-2026-0018', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-03T03:00:00.000Z'),
  ('SS-2026-0018', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 180.00 (quoted RM 180.00 + extra RM 0.00)', '2026-09-03T04:07:00.000Z'),
  ('SS-2026-0018', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Kumaravel S.', '2026-09-03T04:08:00.000Z'),
  ('SS-2026-0018', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 180.00 via DuitNow QR', '2026-09-03T04:09:00.000Z'),
  ('SS-2026-0018', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-04T02:30:00.000Z'),
  ('SS-2026-0018', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-04T03:30:00.000Z'),
  ('SS-2026-0019', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 260.00', '2026-09-04T01:16:00.000Z'),
  ('SS-2026-0019', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-04T02:00:00.000Z'),
  ('SS-2026-0019', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 260.00 (quoted RM 260.00 + extra RM 0.00)', '2026-09-04T07:09:00.000Z'),
  ('SS-2026-0019', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-04T07:10:00.000Z'),
  ('SS-2026-0019', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 260.00 via Bank Transfer', '2026-09-04T07:11:00.000Z'),
  ('SS-2026-0020', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 220.00', '2026-09-04T03:43:00.000Z'),
  ('SS-2026-0020', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-04T04:00:00.000Z'),
  ('SS-2026-0020', 'completed', 'Technician', 'John', 'Job done — final amount RM 220.00 (quoted RM 220.00 + extra RM 0.00)', '2026-09-04T04:49:00.000Z'),
  ('SS-2026-0020', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-04T04:50:00.000Z'),
  ('SS-2026-0020', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-05T02:30:00.000Z'),
  ('SS-2026-0020', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-05T03:30:00.000Z'),
  ('SS-2026-0020', 'rescheduled', 'Admin', 'Admin (desk)', 'Customer not available — rescheduled.', '2026-09-04T06:00:00.000Z'),
  ('SS-2026-0021', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-09-04T02:05:00.000Z'),
  ('SS-2026-0021', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-04T03:00:00.000Z'),
  ('SS-2026-0021', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 150.00 (quoted RM 150.00 + extra RM 0.00)', '2026-09-04T08:58:00.000Z'),
  ('SS-2026-0021', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Lim Chee Keong', '2026-09-04T08:59:00.000Z'),
  ('SS-2026-0021', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-05T02:30:00.000Z'),
  ('SS-2026-0021', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-05T03:30:00.000Z'),
  ('SS-2026-0022', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 260.00', '2026-09-05T02:08:00.000Z'),
  ('SS-2026-0022', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-05T03:00:00.000Z'),
  ('SS-2026-0022', 'completed', 'Technician', 'John', 'Job done — final amount RM 275.00 (quoted RM 260.00 + extra RM 15.00)', '2026-09-05T07:46:00.000Z'),
  ('SS-2026-0022', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Nurul Aina', '2026-09-05T07:47:00.000Z'),
  ('SS-2026-0022', 'payment_recorded', 'Technician', 'John', 'Payment RM 275.00 via DuitNow QR', '2026-09-05T07:48:00.000Z'),
  ('SS-2026-0022', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-06T02:30:00.000Z'),
  ('SS-2026-0023', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 680.00', '2026-09-05T01:35:00.000Z'),
  ('SS-2026-0023', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-05T02:00:00.000Z'),
  ('SS-2026-0023', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 680.00 (quoted RM 680.00 + extra RM 0.00)', '2026-09-05T04:46:00.000Z'),
  ('SS-2026-0023', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-05T04:47:00.000Z'),
  ('SS-2026-0023', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 680.00 via DuitNow QR', '2026-09-05T04:48:00.000Z'),
  ('SS-2026-0023', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-06T02:30:00.000Z'),
  ('SS-2026-0023', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-06T03:30:00.000Z'),
  ('SS-2026-0024', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 120.00', '2026-09-05T03:22:00.000Z'),
  ('SS-2026-0024', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-05T04:00:00.000Z'),
  ('SS-2026-0024', 'completed', 'Technician', 'John', 'Job done — final amount RM 120.00 (quoted RM 120.00 + extra RM 0.00)', '2026-09-05T03:56:00.000Z'),
  ('SS-2026-0024', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Nurul Aina', '2026-09-05T03:57:00.000Z'),
  ('SS-2026-0024', 'payment_recorded', 'Technician', 'John', 'Payment RM 120.00 via Bank Transfer', '2026-09-05T03:58:00.000Z'),
  ('SS-2026-0024', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-06T02:30:00.000Z'),
  ('SS-2026-0024', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-06T03:30:00.000Z'),
  ('SS-2026-0025', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-09-06T04:09:00.000Z'),
  ('SS-2026-0025', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-09-06T05:00:00.000Z'),
  ('SS-2026-0025', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 210.00 (quoted RM 150.00 + extra RM 60.00)', '2026-09-06T06:27:00.000Z'),
  ('SS-2026-0025', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Tan Wei Ling', '2026-09-06T06:28:00.000Z'),
  ('SS-2026-0025', 'payment_recorded', 'Technician', 'Yusoff', 'Payment RM 210.00 via DuitNow QR', '2026-09-06T06:29:00.000Z'),
  ('SS-2026-0025', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-07T02:30:00.000Z'),
  ('SS-2026-0025', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-07T03:30:00.000Z'),
  ('SS-2026-0026', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 220.00', '2026-09-06T04:57:00.000Z'),
  ('SS-2026-0026', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-06T05:00:00.000Z'),
  ('SS-2026-0026', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 220.00 (quoted RM 220.00 + extra RM 0.00)', '2026-09-06T07:49:00.000Z'),
  ('SS-2026-0026', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-06T07:50:00.000Z'),
  ('SS-2026-0027', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 80.00', '2026-09-06T03:09:00.000Z'),
  ('SS-2026-0027', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-06T04:00:00.000Z'),
  ('SS-2026-0027', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 80.00 (quoted RM 80.00 + extra RM 0.00)', '2026-09-06T05:12:00.000Z'),
  ('SS-2026-0027', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-06T05:13:00.000Z'),
  ('SS-2026-0027', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-07T02:30:00.000Z'),
  ('SS-2026-0027', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-07T03:30:00.000Z'),
  ('SS-2026-0028', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 320.00', '2026-09-07T03:29:00.000Z'),
  ('SS-2026-0028', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-07T04:00:00.000Z'),
  ('SS-2026-0028', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 380.00 (quoted RM 320.00 + extra RM 60.00)', '2026-09-07T05:59:00.000Z'),
  ('SS-2026-0028', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Ahmad Zaki', '2026-09-07T06:00:00.000Z'),
  ('SS-2026-0028', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 380.00 via Cash', '2026-09-07T06:01:00.000Z'),
  ('SS-2026-0028', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-08T02:30:00.000Z'),
  ('SS-2026-0028', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-08T03:30:00.000Z'),
  ('SS-2026-0029', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-09-07T01:51:00.000Z'),
  ('SS-2026-0029', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-07T02:00:00.000Z'),
  ('SS-2026-0029', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 150.00 (quoted RM 150.00 + extra RM 0.00)', '2026-09-07T03:07:00.000Z'),
  ('SS-2026-0029', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Syafiq Rahman', '2026-09-07T03:08:00.000Z'),
  ('SS-2026-0029', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 150.00 via Cash', '2026-09-07T03:09:00.000Z'),
  ('SS-2026-0029', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-08T02:30:00.000Z'),
  ('SS-2026-0029', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-08T03:30:00.000Z'),
  ('SS-2026-0030', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-07T01:21:00.000Z'),
  ('SS-2026-0030', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-07T02:00:00.000Z'),
  ('SS-2026-0030', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 450.00 (quoted RM 450.00 + extra RM 0.00)', '2026-09-07T03:26:00.000Z'),
  ('SS-2026-0030', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Rajesh Kumar', '2026-09-07T03:27:00.000Z'),
  ('SS-2026-0030', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 450.00 via DuitNow QR', '2026-09-07T03:28:00.000Z'),
  ('SS-2026-0030', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-08T02:30:00.000Z'),
  ('SS-2026-0030', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-08T03:30:00.000Z'),
  ('SS-2026-0031', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-08T04:49:00.000Z'),
  ('SS-2026-0031', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-08T05:00:00.000Z'),
  ('SS-2026-0031', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 510.00 (quoted RM 450.00 + extra RM 60.00)', '2026-09-08T04:47:00.000Z'),
  ('SS-2026-0031', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Nurul Aina', '2026-09-08T04:48:00.000Z'),
  ('SS-2026-0031', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 510.00 via Bank Transfer', '2026-09-08T04:49:00.000Z'),
  ('SS-2026-0032', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 80.00', '2026-09-08T04:28:00.000Z'),
  ('SS-2026-0032', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-09-08T05:00:00.000Z'),
  ('SS-2026-0032', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 120.00 (quoted RM 80.00 + extra RM 40.00)', '2026-09-08T05:31:00.000Z'),
  ('SS-2026-0032', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-08T05:32:00.000Z'),
  ('SS-2026-0032', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-09T02:30:00.000Z'),
  ('SS-2026-0032', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-09T03:30:00.000Z'),
  ('SS-2026-0033', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 80.00', '2026-09-08T04:08:00.000Z'),
  ('SS-2026-0033', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-08T05:00:00.000Z'),
  ('SS-2026-0033', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 80.00 (quoted RM 80.00 + extra RM 0.00)', '2026-09-08T04:48:00.000Z'),
  ('SS-2026-0033', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Syafiq Rahman', '2026-09-08T04:49:00.000Z'),
  ('SS-2026-0033', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 80.00 via DuitNow QR', '2026-09-08T04:50:00.000Z'),
  ('SS-2026-0033', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-09T02:30:00.000Z'),
  ('SS-2026-0033', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-09T03:30:00.000Z'),
  ('SS-2026-0034', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-09T03:33:00.000Z'),
  ('SS-2026-0034', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-09T04:00:00.000Z'),
  ('SS-2026-0034', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 450.00 (quoted RM 450.00 + extra RM 0.00)', '2026-09-09T03:51:00.000Z'),
  ('SS-2026-0034', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-09T03:52:00.000Z'),
  ('SS-2026-0034', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 450.00 via Bank Transfer', '2026-09-09T03:53:00.000Z'),
  ('SS-2026-0035', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 80.00', '2026-09-09T03:18:00.000Z'),
  ('SS-2026-0035', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-09T04:00:00.000Z'),
  ('SS-2026-0035', 'completed', 'Technician', 'John', 'Job done — final amount RM 80.00 (quoted RM 80.00 + extra RM 0.00)', '2026-09-09T06:45:00.000Z'),
  ('SS-2026-0035', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Lim Chee Keong', '2026-09-09T06:46:00.000Z'),
  ('SS-2026-0035', 'payment_recorded', 'Technician', 'John', 'Payment RM 80.00 via Bank Transfer', '2026-09-09T06:47:00.000Z'),
  ('SS-2026-0035', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-10T02:30:00.000Z'),
  ('SS-2026-0036', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-09T02:28:00.000Z'),
  ('SS-2026-0036', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-09T03:00:00.000Z'),
  ('SS-2026-0036', 'completed', 'Technician', 'John', 'Job done — final amount RM 510.00 (quoted RM 450.00 + extra RM 60.00)', '2026-09-09T06:31:00.000Z'),
  ('SS-2026-0036', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Kumaravel S.', '2026-09-09T06:32:00.000Z'),
  ('SS-2026-0036', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-10T02:30:00.000Z'),
  ('SS-2026-0037', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 680.00', '2026-09-10T04:10:00.000Z'),
  ('SS-2026-0037', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-10T05:00:00.000Z'),
  ('SS-2026-0037', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 680.00 (quoted RM 680.00 + extra RM 0.00)', '2026-09-10T05:09:00.000Z'),
  ('SS-2026-0037', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Ahmad Zaki', '2026-09-10T05:10:00.000Z'),
  ('SS-2026-0037', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 680.00 via DuitNow QR', '2026-09-10T05:11:00.000Z'),
  ('SS-2026-0037', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-11T02:30:00.000Z'),
  ('SS-2026-0038', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 260.00', '2026-09-10T01:10:00.000Z'),
  ('SS-2026-0038', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-10T02:00:00.000Z'),
  ('SS-2026-0038', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 260.00 (quoted RM 260.00 + extra RM 0.00)', '2026-09-10T08:59:00.000Z'),
  ('SS-2026-0038', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Faridah Hassan', '2026-09-10T09:00:00.000Z'),
  ('SS-2026-0038', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 260.00 via Bank Transfer', '2026-09-10T09:01:00.000Z'),
  ('SS-2026-0038', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-11T02:30:00.000Z'),
  ('SS-2026-0038', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-11T03:30:00.000Z'),
  ('SS-2026-0039', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 320.00', '2026-09-10T02:42:00.000Z'),
  ('SS-2026-0039', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-10T03:00:00.000Z'),
  ('SS-2026-0039', 'completed', 'Technician', 'John', 'Job done — final amount RM 335.00 (quoted RM 320.00 + extra RM 15.00)', '2026-09-10T08:27:00.000Z'),
  ('SS-2026-0039', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Rajesh Kumar', '2026-09-10T08:28:00.000Z'),
  ('SS-2026-0039', 'payment_recorded', 'Technician', 'John', 'Payment RM 335.00 via Cash', '2026-09-10T08:29:00.000Z'),
  ('SS-2026-0039', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-11T02:30:00.000Z'),
  ('SS-2026-0039', 'closed', 'Manager', 'Manager', 'Closed.', '2026-09-11T03:30:00.000Z'),
  ('SS-2026-0040', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 260.00', '2026-09-11T01:37:00.000Z'),
  ('SS-2026-0040', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to John', '2026-09-11T02:00:00.000Z'),
  ('SS-2026-0040', 'completed', 'Technician', 'John', 'Job done — final amount RM 320.00 (quoted RM 260.00 + extra RM 60.00)', '2026-09-11T04:16:00.000Z'),
  ('SS-2026-0040', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-11T04:17:00.000Z'),
  ('SS-2026-0040', 'payment_recorded', 'Technician', 'John', 'Payment RM 320.00 via Bank Transfer', '2026-09-11T04:18:00.000Z'),
  ('SS-2026-0041', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 180.00', '2026-09-11T02:43:00.000Z'),
  ('SS-2026-0041', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-09-11T03:00:00.000Z'),
  ('SS-2026-0042', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 320.00', '2026-09-11T04:36:00.000Z'),
  ('SS-2026-0042', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-11T05:00:00.000Z'),
  ('SS-2026-0043', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-12T01:58:00.000Z'),
  ('SS-2026-0043', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Ali', '2026-09-12T02:00:00.000Z'),
  ('SS-2026-0043', 'completed', 'Technician', 'Ali', 'Job done — final amount RM 450.00 (quoted RM 450.00 + extra RM 0.00)', '2026-09-12T08:33:00.000Z'),
  ('SS-2026-0043', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-12T08:34:00.000Z'),
  ('SS-2026-0043', 'payment_recorded', 'Technician', 'Ali', 'Payment RM 450.00 via Cash', '2026-09-12T08:35:00.000Z'),
  ('SS-2026-0044', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 150.00', '2026-09-12T02:18:00.000Z'),
  ('SS-2026-0044', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Bala', '2026-09-12T03:00:00.000Z'),
  ('SS-2026-0044', 'completed', 'Technician', 'Bala', 'Job done — final amount RM 150.00 (quoted RM 150.00 + extra RM 0.00)', '2026-09-12T07:00:00.000Z'),
  ('SS-2026-0044', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Wong Kah Meng', '2026-09-12T07:01:00.000Z'),
  ('SS-2026-0044', 'payment_recorded', 'Technician', 'Bala', 'Payment RM 150.00 via DuitNow QR', '2026-09-12T07:02:00.000Z'),
  ('SS-2026-0044', 'reviewed', 'Manager', 'Manager', 'Reviewed and approved.', '2026-09-12T02:30:00.000Z'),
  ('SS-2026-0045', 'created', 'Admin', 'Admin (desk)', 'Order created with quoted price RM 450.00', '2026-09-12T01:21:00.000Z'),
  ('SS-2026-0045', 'assigned', 'Admin', 'Admin (desk)', 'Assigned to Yusoff', '2026-09-12T02:00:00.000Z'),
  ('SS-2026-0045', 'completed', 'Technician', 'Yusoff', 'Job done — final amount RM 450.00 (quoted RM 450.00 + extra RM 0.00)', '2026-09-12T03:42:00.000Z'),
  ('SS-2026-0045', 'notified', 'System', 'Notifier', 'WhatsApp message prepared for Syafiq Rahman', '2026-09-12T03:43:00.000Z');

insert into notifications (order_no, channel, target, message, status, deep_link, created_at) values
  ('SS-2026-0002', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0002 has been completed by Technician Ali at 29 Aug 2026, 03:06 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0002%20has%20been%20completed%20by%20Technician%20Ali%20at%2029%20Aug%202026%2C%2003%3A06%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-29T07:07:00.000Z'),
  ('SS-2026-0003', 'whatsapp', '016-2233445', 'Hi Lim Chee Keong,

Job SS-2026-0003 has been completed by Technician Bala at 29 Aug 2026, 02:48 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60162233445?text=Hi%20Lim%20Chee%20Keong%2C%0A%0AJob%20SS-2026-0003%20has%20been%20completed%20by%20Technician%20Bala%20at%2029%20Aug%202026%2C%2002%3A48%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-29T06:49:00.000Z'),
  ('SS-2026-0004', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0004 has been completed by Technician Ali at 30 Aug 2026, 04:09 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0004%20has%20been%20completed%20by%20Technician%20Ali%20at%2030%20Aug%202026%2C%2004%3A09%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-30T08:10:00.000Z'),
  ('SS-2026-0005', 'whatsapp', '012-3456789', 'Hi Ahmad Zaki,

Job SS-2026-0005 has been completed by Technician Bala at 30 Aug 2026, 12:31 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60123456789?text=Hi%20Ahmad%20Zaki%2C%0A%0AJob%20SS-2026-0005%20has%20been%20completed%20by%20Technician%20Bala%20at%2030%20Aug%202026%2C%2012%3A31%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-30T04:32:00.000Z'),
  ('SS-2026-0006', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0006 has been completed by Technician Yusoff at 30 Aug 2026, 04:03 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0006%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2030%20Aug%202026%2C%2004%3A03%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-30T08:04:00.000Z'),
  ('SS-2026-0007', 'whatsapp', '019-3344556', 'Hi Tan Wei Ling,

Job SS-2026-0007 has been completed by Technician Yusoff at 31 Aug 2026, 11:53 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60193344556?text=Hi%20Tan%20Wei%20Ling%2C%0A%0AJob%20SS-2026-0007%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2031%20Aug%202026%2C%2011%3A53%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-31T03:54:00.000Z'),
  ('SS-2026-0008', 'whatsapp', '012-9988776', 'Hi Kumaravel S.,

Job SS-2026-0008 has been completed by Technician Yusoff at 31 Aug 2026, 12:10 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60129988776?text=Hi%20Kumaravel%20S.%2C%0A%0AJob%20SS-2026-0008%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2031%20Aug%202026%2C%2012%3A10%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-08-31T04:11:00.000Z'),
  ('SS-2026-0010', 'whatsapp', '014-8899001', 'Hi Syafiq Rahman,

Job SS-2026-0010 has been completed by Technician Bala at 01 Sept 2026, 02:23 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60148899001?text=Hi%20Syafiq%20Rahman%2C%0A%0AJob%20SS-2026-0010%20has%20been%20completed%20by%20Technician%20Bala%20at%2001%20Sept%202026%2C%2002%3A23%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-01T06:24:00.000Z'),
  ('SS-2026-0011', 'whatsapp', '016-2233445', 'Hi Lim Chee Keong,

Job SS-2026-0011 has been completed by Technician Yusoff at 01 Sept 2026, 03:05 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60162233445?text=Hi%20Lim%20Chee%20Keong%2C%0A%0AJob%20SS-2026-0011%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2001%20Sept%202026%2C%2003%3A05%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-01T07:06:00.000Z'),
  ('SS-2026-0012', 'whatsapp', '012-9988776', 'Hi Kumaravel S.,

Job SS-2026-0012 has been completed by Technician John at 01 Sept 2026, 04:13 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60129988776?text=Hi%20Kumaravel%20S.%2C%0A%0AJob%20SS-2026-0012%20has%20been%20completed%20by%20Technician%20John%20at%2001%20Sept%202026%2C%2004%3A13%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-01T08:14:00.000Z'),
  ('SS-2026-0013', 'whatsapp', '012-9988776', 'Hi Kumaravel S.,

Job SS-2026-0013 has been completed by Technician Ali at 02 Sept 2026, 01:03 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60129988776?text=Hi%20Kumaravel%20S.%2C%0A%0AJob%20SS-2026-0013%20has%20been%20completed%20by%20Technician%20Ali%20at%2002%20Sept%202026%2C%2001%3A03%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-02T05:04:00.000Z'),
  ('SS-2026-0014', 'whatsapp', '014-8899001', 'Hi Syafiq Rahman,

Job SS-2026-0014 has been completed by Technician Ali at 02 Sept 2026, 11:54 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60148899001?text=Hi%20Syafiq%20Rahman%2C%0A%0AJob%20SS-2026-0014%20has%20been%20completed%20by%20Technician%20Ali%20at%2002%20Sept%202026%2C%2011%3A54%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-02T03:55:00.000Z'),
  ('SS-2026-0016', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0016 has been completed by Technician Ali at 03 Sept 2026, 03:49 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0016%20has%20been%20completed%20by%20Technician%20Ali%20at%2003%20Sept%202026%2C%2003%3A49%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-03T07:50:00.000Z'),
  ('SS-2026-0017', 'whatsapp', '017-5566778', 'Hi Rajesh Kumar,

Job SS-2026-0017 has been completed by Technician John at 03 Sept 2026, 02:57 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60175566778?text=Hi%20Rajesh%20Kumar%2C%0A%0AJob%20SS-2026-0017%20has%20been%20completed%20by%20Technician%20John%20at%2003%20Sept%202026%2C%2002%3A57%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-03T06:58:00.000Z'),
  ('SS-2026-0018', 'whatsapp', '012-9988776', 'Hi Kumaravel S.,

Job SS-2026-0018 has been completed by Technician Ali at 03 Sept 2026, 12:07 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60129988776?text=Hi%20Kumaravel%20S.%2C%0A%0AJob%20SS-2026-0018%20has%20been%20completed%20by%20Technician%20Ali%20at%2003%20Sept%202026%2C%2012%3A07%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-03T04:08:00.000Z'),
  ('SS-2026-0019', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0019 has been completed by Technician Ali at 04 Sept 2026, 03:09 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0019%20has%20been%20completed%20by%20Technician%20Ali%20at%2004%20Sept%202026%2C%2003%3A09%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-04T07:10:00.000Z'),
  ('SS-2026-0020', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0020 has been completed by Technician John at 04 Sept 2026, 12:49 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0020%20has%20been%20completed%20by%20Technician%20John%20at%2004%20Sept%202026%2C%2012%3A49%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-04T04:50:00.000Z'),
  ('SS-2026-0021', 'whatsapp', '016-2233445', 'Hi Lim Chee Keong,

Job SS-2026-0021 has been completed by Technician Bala at 04 Sept 2026, 04:58 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60162233445?text=Hi%20Lim%20Chee%20Keong%2C%0A%0AJob%20SS-2026-0021%20has%20been%20completed%20by%20Technician%20Bala%20at%2004%20Sept%202026%2C%2004%3A58%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-04T08:59:00.000Z'),
  ('SS-2026-0022', 'whatsapp', '018-7766554', 'Hi Nurul Aina,

Job SS-2026-0022 has been completed by Technician John at 05 Sept 2026, 03:46 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60187766554?text=Hi%20Nurul%20Aina%2C%0A%0AJob%20SS-2026-0022%20has%20been%20completed%20by%20Technician%20John%20at%2005%20Sept%202026%2C%2003%3A46%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-05T07:47:00.000Z'),
  ('SS-2026-0023', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0023 has been completed by Technician Bala at 05 Sept 2026, 12:46 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0023%20has%20been%20completed%20by%20Technician%20Bala%20at%2005%20Sept%202026%2C%2012%3A46%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-05T04:47:00.000Z'),
  ('SS-2026-0024', 'whatsapp', '018-7766554', 'Hi Nurul Aina,

Job SS-2026-0024 has been completed by Technician John at 05 Sept 2026, 11:56 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60187766554?text=Hi%20Nurul%20Aina%2C%0A%0AJob%20SS-2026-0024%20has%20been%20completed%20by%20Technician%20John%20at%2005%20Sept%202026%2C%2011%3A56%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-05T03:57:00.000Z'),
  ('SS-2026-0025', 'whatsapp', '019-3344556', 'Hi Tan Wei Ling,

Job SS-2026-0025 has been completed by Technician Yusoff at 06 Sept 2026, 02:27 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60193344556?text=Hi%20Tan%20Wei%20Ling%2C%0A%0AJob%20SS-2026-0025%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2006%20Sept%202026%2C%2002%3A27%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-06T06:28:00.000Z'),
  ('SS-2026-0026', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0026 has been completed by Technician Bala at 06 Sept 2026, 03:49 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0026%20has%20been%20completed%20by%20Technician%20Bala%20at%2006%20Sept%202026%2C%2003%3A49%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-06T07:50:00.000Z'),
  ('SS-2026-0027', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0027 has been completed by Technician Bala at 06 Sept 2026, 01:12 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0027%20has%20been%20completed%20by%20Technician%20Bala%20at%2006%20Sept%202026%2C%2001%3A12%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-06T05:13:00.000Z'),
  ('SS-2026-0028', 'whatsapp', '012-3456789', 'Hi Ahmad Zaki,

Job SS-2026-0028 has been completed by Technician Bala at 07 Sept 2026, 01:59 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60123456789?text=Hi%20Ahmad%20Zaki%2C%0A%0AJob%20SS-2026-0028%20has%20been%20completed%20by%20Technician%20Bala%20at%2007%20Sept%202026%2C%2001%3A59%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-07T06:00:00.000Z'),
  ('SS-2026-0029', 'whatsapp', '014-8899001', 'Hi Syafiq Rahman,

Job SS-2026-0029 has been completed by Technician Bala at 07 Sept 2026, 11:07 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60148899001?text=Hi%20Syafiq%20Rahman%2C%0A%0AJob%20SS-2026-0029%20has%20been%20completed%20by%20Technician%20Bala%20at%2007%20Sept%202026%2C%2011%3A07%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-07T03:08:00.000Z'),
  ('SS-2026-0030', 'whatsapp', '017-5566778', 'Hi Rajesh Kumar,

Job SS-2026-0030 has been completed by Technician Ali at 07 Sept 2026, 11:26 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60175566778?text=Hi%20Rajesh%20Kumar%2C%0A%0AJob%20SS-2026-0030%20has%20been%20completed%20by%20Technician%20Ali%20at%2007%20Sept%202026%2C%2011%3A26%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-07T03:27:00.000Z'),
  ('SS-2026-0031', 'whatsapp', '018-7766554', 'Hi Nurul Aina,

Job SS-2026-0031 has been completed by Technician Ali at 08 Sept 2026, 12:47 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60187766554?text=Hi%20Nurul%20Aina%2C%0A%0AJob%20SS-2026-0031%20has%20been%20completed%20by%20Technician%20Ali%20at%2008%20Sept%202026%2C%2012%3A47%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-08T04:48:00.000Z'),
  ('SS-2026-0032', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0032 has been completed by Technician Yusoff at 08 Sept 2026, 01:31 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0032%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2008%20Sept%202026%2C%2001%3A31%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-08T05:32:00.000Z'),
  ('SS-2026-0033', 'whatsapp', '014-8899001', 'Hi Syafiq Rahman,

Job SS-2026-0033 has been completed by Technician Bala at 08 Sept 2026, 12:48 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60148899001?text=Hi%20Syafiq%20Rahman%2C%0A%0AJob%20SS-2026-0033%20has%20been%20completed%20by%20Technician%20Bala%20at%2008%20Sept%202026%2C%2012%3A48%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-08T04:49:00.000Z'),
  ('SS-2026-0034', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0034 has been completed by Technician Ali at 09 Sept 2026, 11:51 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0034%20has%20been%20completed%20by%20Technician%20Ali%20at%2009%20Sept%202026%2C%2011%3A51%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-09T03:52:00.000Z'),
  ('SS-2026-0035', 'whatsapp', '016-2233445', 'Hi Lim Chee Keong,

Job SS-2026-0035 has been completed by Technician John at 09 Sept 2026, 02:45 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60162233445?text=Hi%20Lim%20Chee%20Keong%2C%0A%0AJob%20SS-2026-0035%20has%20been%20completed%20by%20Technician%20John%20at%2009%20Sept%202026%2C%2002%3A45%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-09T06:46:00.000Z'),
  ('SS-2026-0036', 'whatsapp', '012-9988776', 'Hi Kumaravel S.,

Job SS-2026-0036 has been completed by Technician John at 09 Sept 2026, 02:31 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60129988776?text=Hi%20Kumaravel%20S.%2C%0A%0AJob%20SS-2026-0036%20has%20been%20completed%20by%20Technician%20John%20at%2009%20Sept%202026%2C%2002%3A31%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-09T06:32:00.000Z'),
  ('SS-2026-0037', 'whatsapp', '012-3456789', 'Hi Ahmad Zaki,

Job SS-2026-0037 has been completed by Technician Ali at 10 Sept 2026, 01:09 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60123456789?text=Hi%20Ahmad%20Zaki%2C%0A%0AJob%20SS-2026-0037%20has%20been%20completed%20by%20Technician%20Ali%20at%2010%20Sept%202026%2C%2001%3A09%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-10T05:10:00.000Z'),
  ('SS-2026-0038', 'whatsapp', '011-22334455', 'Hi Faridah Hassan,

Job SS-2026-0038 has been completed by Technician Ali at 10 Sept 2026, 04:59 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/601122334455?text=Hi%20Faridah%20Hassan%2C%0A%0AJob%20SS-2026-0038%20has%20been%20completed%20by%20Technician%20Ali%20at%2010%20Sept%202026%2C%2004%3A59%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-10T09:00:00.000Z'),
  ('SS-2026-0039', 'whatsapp', '017-5566778', 'Hi Rajesh Kumar,

Job SS-2026-0039 has been completed by Technician John at 10 Sept 2026, 04:27 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60175566778?text=Hi%20Rajesh%20Kumar%2C%0A%0AJob%20SS-2026-0039%20has%20been%20completed%20by%20Technician%20John%20at%2010%20Sept%202026%2C%2004%3A27%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-10T08:28:00.000Z'),
  ('SS-2026-0040', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0040 has been completed by Technician John at 11 Sept 2026, 12:16 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0040%20has%20been%20completed%20by%20Technician%20John%20at%2011%20Sept%202026%2C%2012%3A16%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-11T04:17:00.000Z'),
  ('SS-2026-0043', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0043 has been completed by Technician Ali at 12 Sept 2026, 04:33 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0043%20has%20been%20completed%20by%20Technician%20Ali%20at%2012%20Sept%202026%2C%2004%3A33%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-12T08:34:00.000Z'),
  ('SS-2026-0044', 'whatsapp', '016-1122334', 'Hi Wong Kah Meng,

Job SS-2026-0044 has been completed by Technician Bala at 12 Sept 2026, 03:00 pm.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60161122334?text=Hi%20Wong%20Kah%20Meng%2C%0A%0AJob%20SS-2026-0044%20has%20been%20completed%20by%20Technician%20Bala%20at%2012%20Sept%202026%2C%2003%3A00%20pm.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-12T07:01:00.000Z'),
  ('SS-2026-0045', 'whatsapp', '014-8899001', 'Hi Syafiq Rahman,

Job SS-2026-0045 has been completed by Technician Yusoff at 12 Sept 2026, 11:42 am.
Please check and leave feedback.

Thank you!', 'prepared', 'https://wa.me/60148899001?text=Hi%20Syafiq%20Rahman%2C%0A%0AJob%20SS-2026-0045%20has%20been%20completed%20by%20Technician%20Yusoff%20at%2012%20Sept%202026%2C%2011%3A42%20am.%0APlease%20check%20and%20leave%20feedback.%0A%0AThank%20you!', '2026-09-12T03:43:00.000Z');

commit;
