/**
 * Generates supabase/seed.sql from the SAME deterministic dataset the browser
 * demo uses (src/lib/seed.ts), so the live demo and the cloud deployment show
 * identical numbers — which matters when the reviewer asks the AI
 * "which technician did the most jobs last week?" in either mode.
 *
 * Run:  npm run seed:sql      (node --experimental-strip-types)
 */
import { writeFileSync } from 'node:fs';
import { buildSeed } from '../src/lib/seed';

const { orders, reports, events, notifications } = buildSeed({ today: new Date('2026-09-12T09:00:00+08:00') });

const q = (s: string) => `'${String(s).replace(/'/g, "''")}'`;
const n = (v: number | null) => (v === null ? 'null' : String(v));

const lines: string[] = [];
lines.push('-- AUTO-GENERATED by scripts/generate-seed-sql.ts — do not edit by hand.');
lines.push('-- Deterministic demo dataset shared with the browser demo mode.');
lines.push('-- Run schema.sql first, then this file.');
lines.push('');
lines.push('begin;');
lines.push('');
lines.push('-- Idempotent: wipe only the demo tables, keep the schema.');
lines.push('truncate table notifications, order_events, attachments, service_reports, orders cascade;');
lines.push('');

lines.push('insert into orders (order_no, customer_name, phone, address, problem_description, service_type, quoted_price, assigned_technician, status, admin_notes, created_at, updated_at) values');
lines.push(
  orders
    .map(
      (o) =>
        `  (${q(o.order_no)}, ${q(o.customer_name)}, ${q(o.phone)}, ${q(o.address)}, ${q(o.problem_description)}, ${q(
          o.service_type,
        )}, ${o.quoted_price}, ${o.assigned_technician ? q(o.assigned_technician) : 'null'}, ${q(o.status)}, ${q(
          o.admin_notes,
        )}, ${q(o.created_at)}, ${q(o.updated_at)})`,
    )
    .join(',\n') + ';',
);
lines.push('');

if (reports.length) {
  lines.push('insert into service_reports (order_no, work_done, extra_charges, final_amount, remarks, technician_name, completed_at, payment_amount, payment_method) values');
  lines.push(
    reports
      .map(
        (r) =>
          `  (${q(r.order_no)}, ${q(r.work_done)}, ${r.extra_charges}, ${r.final_amount}, ${q(r.remarks)}, ${q(
            r.technician_name,
          )}, ${q(r.completed_at)}, ${n(r.payment_amount)}, ${r.payment_method ? q(r.payment_method) : 'null'})`,
      )
      .join(',\n') + ';',
  );
  lines.push('');

  const attachmentRows = reports.flatMap((r) => r.attachments.map((a) => `  (${q(r.order_no)}, ${q(a.name)}, ${q(a.mime)}, ${a.size}, ${q(a.url)})`));
  if (attachmentRows.length) {
    lines.push('-- Attachment rows are linked by order_no because the report UUIDs are generated by the database.');
    lines.push('insert into attachments (report_id, name, mime, size, url)');
    lines.push('select sr.id, v.name, v.mime, v.size, v.url');
    lines.push('from (values');
    lines.push(attachmentRows.join(',\n'));
    lines.push(') as v(order_no, name, mime, size, url)');
    lines.push('join service_reports sr on sr.order_no = v.order_no;');
    lines.push('');
  }
}

lines.push('insert into order_events (order_no, event_type, actor_role, actor_name, detail, created_at) values');
lines.push(
  events
    .map(
      (e) =>
        `  (${q(e.order_no)}, ${q(e.event_type)}, ${q(e.actor_role)}, ${q(e.actor_name)}, ${q(e.detail)}, ${q(e.created_at)})`,
    )
    .join(',\n') + ';',
);
lines.push('');

if (notifications.length) {
  lines.push('insert into notifications (order_no, channel, target, message, status, deep_link, created_at) values');
  lines.push(
    notifications
      .map(
        (x) =>
          `  (${q(x.order_no)}, ${q(x.channel)}, ${q(x.target)}, ${q(x.message)}, ${q(x.status)}, ${q(x.deep_link)}, ${q(
            x.created_at,
          )})`,
      )
      .join(',\n') + ';',
  );
  lines.push('');
}

lines.push('commit;');
lines.push('');

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n'), 'utf8');
console.log(
  `seed.sql written: ${orders.length} orders, ${reports.length} reports, ${events.length} events, ${notifications.length} notifications`,
);
